name: CI/CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Node.js setup
      uses: actions/setup-node@v2
      with:
        node-version: '24'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      env:
        FORCE_COLOR: 1
      run: |
        npm run check > test-results.log 
        cat test-results.log
    - name: Upload test results 
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: test-results.log
  Deploy:
   runs-on: ubuntu-latest
   needs: Test
   steps: 
    - name: Connect EC2 Instance
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/app
          git pull origin main
          npm install
          pm2 restart --name "APP:3000" npm -- start
          pm2 save
          sudo systemctl restart nginx 
